# Browser App
# Displays web search and reading activity from AI agents

id: browser
name: Browser
icon: globe
description: Watch AI search the web and read pages

# Entity types this app displays
entities:
  - webpage

views:
  # Search results view - shows webpage.search activities
  search:
    entity: webpage
    operation: search
    title: Browser
    toolbar:
      - component: url-bar
        props:
          mode: search
          value: "{{activity.request.query}}"
          source: "{{activity.connector}}"
          sourceIcon: "/plugins/{{activity.connector}}/icon.png"
    
    layout:
      - component: list
        data:
          source: activity
        item_component: items/search-result
        item_props:
          title: "{{title}}"
          url: "{{url}}"
          snippet: "{{snippet}}"
        footer:
          count: "{{activity.response.length}}"
          source: "{{activity.connector}}"
          duration: "{{activity.duration_ms}}"

  # Read view - shows webpage.read activities
  read:
    entity: webpage
    operation: read
    title: "{{activity.response.title}}"
    toolbar:
      - component: url-bar
        props:
          mode: url
          value: "{{activity.request.url}}"
          source: "{{activity.connector}}"
          sourceIcon: "/plugins/{{activity.connector}}/icon.png"
    
    layout:
      - component: layout/scroll-area
        children:
          - component: markdown
            props:
              content: "{{activity.response.content}}"
        footer:
          source: "{{activity.connector}}"
          duration: "{{activity.duration_ms}}"

default_view: search
